# REQUIRED VARIABLES:
# These installation-specific variables must be set in the external pipeline 
# variables
#
# - azureServiceConnectionName: Name of the service connection which has
#     permission to deploy to the function app
# - azureAppServiceName: Name of the function service in your Azure subscription

trigger:
  branches:
    include:
    - main

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  application: SampleFunctionApp

steps:
- template: steps/build.yaml
- template: steps/test.yaml
- template: steps/publish.yaml
- template: steps/deploy.yaml
