# REQUIRED VARIABLES:
# - azureServiceConnectionName

trigger:
  branches:
    include:
    - main

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureAppServiceName: 'fn-4ysmefwmvwibk'

steps:
- template: steps/build.yaml
- template: steps/test.yaml
- template: steps/publish.yaml
#- template: steps/release.yaml
